version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: chat-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongopass
      MONGO_INITDB_DATABASE: chatdb
    command: ["mongod", "--bind_ip_all"]
    volumes:
      - mongodb_data:/data/db

  postgres:
    image: postgres:latest
    container_name: chat-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: userdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  mongodb_data:
  postgres_data: